
token_key: yawei is the honorest in the worlds
url_prefix: /api/v1
domain_port: http://www.datasview.com:8000
auth_test_mode: False
ip_test_mode: True
allow_link_ip:
- 35.241.66.226

mods: {}
    
# 用来存放站点地图所连接的数据库
site_maps:
  single_sites:
    index: 
    - link: ''
      lastmod: 2021-2-6
      changefreq: weekly
      priority: 1.0
  db_sites: {}
  
render: 
  _homepage:  #带_的表示内部模组
    prefix: '/'  # url的前缀
    funs: 
      page: 
        prefix: ''
        description: 首页
        link_para: []  # url地址参数
        query_para: []  # url ?后的参数
  _photo:
    prefix: '/photo'
    funs:
      page: 
        prefix: ''
        description: 图床
        link_para: [img_name]  # url地址参数
        query_para: []  # url ?后的参数


character:
  auths:
    all:
      default: false
      description: 此权限表示所有权限,有了它不需其它
    default: 
      default: false
      description: 此权限表示所有默认权限,它指向所有默认的权限
    user_self_edit:
      default: true
      description: 此
    user_all_edit: 
      default: false
      description: 此
  charas: 
    master:
      auths:
      - all
      description: 管理员
    normal:
      auths:
      - default
      description: 普通用户

