token_key: yawei is the honorest in the worlds
url_prefix: /api/v1
domain_port: http://dev.datasview.com:8080
host: dev.datasview.com:8080
is_https: True
ip_test_mode: True # 开启时允许所有的ip访问、オンにすると全部IPアドレスを受け入れる
route_test_mode: True # 是否显示测试路由、テストモジュールをオンにするか

# 开启时将返回错误的详细信息(严重)
# オンにするとエラーメッセージがリターンされる、絶対本番環境ではオフにしてください
err_test_mode: True
assets_path: files/assets
allow_link_ip:
  - 35.241.66.226

# don't delete it
mods: [ ]
