
token_key: yawei is the honorest in the worlds
url_prefix: /api/v1
domain_port: http://www.datasview.com:8000
auth_test_mode: True
ip_test_mode: True
allow_link_ip:
- 35.241.66.226

mods: 
  sitemap:
    status: unused
    name: sitemap
    version: 1
    has_mdl: False
    has_sitemap: False
    route: 
      route_prefix: sitemap
      tags: 
      - 网页地图
    
# 用来存放站点地图所连接的数据库
site_maps:
  single_sites:
    index: 
    - link: ''
      lastmod: 2021-2-6
      changefreq: weekly
      priority: 1.0
  db_sites: {}
  
render: 
  _homepage:  #带_的表示内部模组
    prefix: '/'  # url的前缀
    funs: 
      page: 
        prefix: ''
        description: 首页
        link_para: []  # url地址参数
        query_para: []  # url ?后的参数



